/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package test.client2.api;

import test.client2.dto.Users2PostRequest;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-02-12T15:21:48.632152+01:00[Europe/Berlin]")
@Validated
public interface Users2Api {

    /**
     * POST /users2 : Adds a new user
     *
     * @param users2PostRequest  (optional)
     * @return OK (status code 200)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/users2",
        consumes = "application/json"
    )
    
    ResponseEntity<Void> users2Post(
         @Valid @RequestBody(required = false) Optional<Users2PostRequest> users2PostRequest
    );

}
