---
openapi: 3.0.3
info:
  title: Test
  version: v2
  description: Test
security:
  - oauth2: [ ]
paths:
  /users2:
    post:
      summary: Adds a new user
      requestBody:
        content:
          application/json:
            schema: # Request body contents
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
              example: # Sample object
                id: 10
                name: Jessica Smith
      responses:
        '200':
          description: OK

components:
  securitySchemes:
    oauth2:
      $ref: 'core-api.yaml#/components/securitySchemes/test'
